version: '2'
services:
    jbpmcuy-app:
        image: jbpmcuy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jbpmcuy-postgresql:5432/jbpmcuy
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jbpmcuy-postgresql:
        extends:
            file: postgresql.yml
            service: jbpmcuy-postgresql
